#!/bin/sh
set -o errexit

source ./git.sh
source ./python.sh
source ./zsh.sh

print_help () {
    echo "Good luck lol"
    exit 0
}

essentials () {
    # GCC and Makefile
    echo "Installing GNU tools..."
    sudo apt install gcc make curl wget -y
    sudo apt install build-essential libssl-dev libffi-dev -y
    sudo apt install apt-transport-https ca-certificates software-properties-common -y
    # Gnome tweaks and extensions
    echo "Installing Gnome tweaks..."
    sudo apt install gnome-tweaks gnome-shell-extensions chrome-gnome-shell -y
}

custom_configs () {
    # wrapping up extra configurations
    echo "Setting up extra configurations..."
    mkdir -p ${HOME}/.aliases
    mkdir -p ${HOME}/.aliases/.private-configs
    ln -f ../../zsh/.aliases/.* ${HOME}/.aliases
    ln -f ../../zsh/.zshrc ${HOME}/.zshrc
    ln -f .private-configs/* ${HOME}/.private-configs/*
    ln -f ../../vscode/settings.json ${HOME}/.config/Code/User/settings.json
}

while [ ! $# -eq 0 ]
do
    case "$1" in

        --all)
            essentials
            setup_git
            setup_zsh
            py_dev
            custom_configs
            ;;

        --help | -h | --please-help | --wtf-is-this)
            print_help
            ;;

        --vm)
            # VM guest tools
            echo "Installing VM Tools..."
            sudo apt install open-vm-tools-desktop -y
            ;;

        --sys)
            essentials
            ;;

        --git)
            setup_git
            ;;

        --subl)
            setup_subl
            ;;

        --zsh)
            setup_zsh
            ;;

        --python)
            py_dev
            ;;

        --custom)
            custom_configs
            ;;

        *)
            echo "Invalid args"
            exit 1
            ;;

    esac
    shift
done
