#!/bin/sh
set -o errexit

setup_subl () {
    # Sublime Text
    echo "Installing Sublime Text..."
    curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
    sudo add-apt-repository "deb https://download.sublimetext.com/ apt/stable/"
    sudo apt update && sudo apt install sublime-text
}
